alter table AUTO_USER_EXT add constraint FK_AUTO_USER_EXT_ON_COUNTRY_CODE foreign key (COUNTRY_CODE_ID) references AUTO_COUNTRY(ID);
create index IDX_AUTO_USER_EXT_ON_COUNTRY_CODE on AUTO_USER_EXT (COUNTRY_CODE_ID);
